version: '3.6'
services:
  app:
    build:
      context: .
      dockerfile: ./DockerFiles/Federation/Dockerfile
    image: fed:latest
    restart: always
    environment:
        AUTH: "Token"
    volumes:
      - ./backend:/var/www/app
  caddy:
    build:
      context: .
      dockerfile: ./DockerFiles/Caddy/Dockerfile
    image: fed_caddy:latest
    depends_on:
      - "app"
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend/build:/var/www/app
      - ./Caddy/local-Caddyfile:/etc/caddy/Caddyfile
      - caddy_certs:/root/.caddy
volumes:
  db_data:
  caddy_certs:
